### ISSUE TITLE
Translation issue for order by with distinct

### ISSUE THREAD

**Issue by erikest** [ProjectNami/projectnami#143] opened 2016-10-18 00:40 UTC
Getting the following in my translate.log:

2016-10-18 00:21:44 Error Code: 145 -- Begin Query translation attempt:
SELECT  DISTINCT t.*, tt.* FROM wp_terms AS t  INNER JOIN wp_term_taxonomy AS tt ON t.term_id = tt.term_id LEFT JOIN wp_termmeta AS tm ON (t.term_id = tm.term_id AND tm.meta_key = 'order')  WHERE tt.taxonomy IN ('product_cat') ORDER BY tm.meta_value+0 ASC, t.name ASC 
2016-10-18 00:21:44 -- Translation result:
SELECT  DISTINCT t.*, tt.* FROM wp_terms AS t  INNER JOIN wp_term_taxonomy AS tt ON t.term_id = tt.term_id LEFT JOIN wp_termmeta AS tm ON (t.term_id = tm.term_id AND tm.meta_key = 'order')  WHERE tt.taxonomy IN ('product_cat') ORDER BY t, tt, tm ASC, t.name ASC

So far as I can tell, this is happening in translate_distinct_orderby which calls get_as_fields.  Looks like that function is plucking out the table aliases, where it only wants the column aliases.  One way to fix it would be to pass in only the first part of the select clause and leave off everything after the 'FROM'.  Need to handle nested queries too though...

**Comment by erikest** [comment] 2016-10-18 00:55
Tried that, but this case is more complicated because the select statement uses wildcards and the order by can't use columns not listed in the select clause, which is another error, 145.  I'll handle this in a special case for now, but there are then two problems:

- get_as_fields gets both column and table aliases, should get just column aliases

- need to add 'order by' columns to the 'select' clause, if they're not already present

**Comment by patrickebates** [comment] 2016-10-18 01:01
Does the PHP error log showed what called this?  It looks like a core function that we have updated at least once before.  Wondering if we have a regression error here.

**Comment by patrickebates** [comment] 2016-10-18 01:09
Found 4 possible instances and updated them

**Comment by patrickebates** [comment] 2016-10-19 18:47
These updates for meta_value sorting shipped in 1.4.3.  Please close this case if the issue is now resolved.

**Closed** 2017-03-14 16:14 UTC
